jobs:
- name: spanish
  plan:
  - task: say-hola
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args: ["Hola Amigos!"]
